name: CI

on:
  push:
    branches:
      - main
      - addtests
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test -v -cover ./...
        env:
          GOFLAGS: -mod=mod

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install Staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run gofmt
        run: test -z "$(gofmt -l . | tee /dev/stderr)"

      - name: Run go vet
        run: go vet ./...
        env:
          GOFLAGS: -mod=mod

      - name: Run staticcheck
        run: staticcheck ./...
        env:
          GOFLAGS: -mod=mod

  security:
    name: Security
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install Gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run Gosec
        run: ~/go/bin/gosec ./...
        env:
          GOFLAGS: -mod=mod

