name: ci

on:
  push:
    branches:
      - main
      - addtests
  pull_request:

jobs:
  Tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run tests with code coverage
        run: go test -cover ./...

  Style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run go fmt
        run: test -z "$(go fmt ./...)"

