name: ci

on:
  push:
    branches:
      - main
      - addtests
  pull_request:

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go 1.22
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Run tests with code coverage
        run: go test -cover ./...

  Style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go 1.22
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Check formatting with go fmt
        run: test -z "$(go fmt ./...)"

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

