name: CI

on:
  push:
    branches: [main, addtests]
  pull_request:
    branches: [main]

jobs:
  Tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install dependencies
        run: go mod tidy

      - name: Run unit tests
        run: go test -cover ./...

  Style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Check formatting
        run: |
          output=$(go fmt ./...)
          if [ -n "$output" ]; then
            echo "Code formatting issues:"
            echo "$output"
            exit 1
          fi

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: $HOME/go/bin/staticcheck ./...

  Security:
    name: Security
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec
        run: $HOME/go/bin/gosec ./...

